#!/usr/bin/env python3
"""Inspect the exact x-is-human header generated by BotID on meta.matcha.xyz."""
import json
import time
from urllib.parse import urlparse
from patchright.sync_api import sync_playwright

PROXY_URL = "http://COlBMQ:bCYTai@14.224.225.135:45376"
p = urlparse(PROXY_URL)
p_cfg = {"server": f"{p.scheme}://{p.hostname}:{p.port}", "username": p.username, "password": p.password}

with sync_playwright() as pw:
    b = pw.chromium.launch(headless=False, args=["--headless=new", "--no-sandbox"], proxy=p_cfg)
    c = b.new_context(user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36")
    page = c.new_page()
    
    captured_headers = []
    page.on("request", lambda r: captured_headers.append(dict(r.headers)) if "competitions" in r.url else None)
    
    print("Navigating to https://meta.matcha.xyz/ethereum...")
    page.goto("https://meta.matcha.xyz/ethereum", wait_until="domcontentloaded", timeout=35000)
    
    for _ in range(25):
        time.sleep(1)
        if "checkpoint" not in (page.title() or "").lower() and len(page.title() or "") > 0:
            break
            
    print("Title:", page.title())
    time.sleep(3)
    
    # Simulate user movement
    page.mouse.move(200, 200)
    time.sleep(0.2)
    page.mouse.move(500, 400, steps=10)
    time.sleep(0.5)
    page.mouse.click(500, 400)
    time.sleep(1.0)
    
    # Call fetch('/api/competitions')
    res = page.evaluate("""async () => {
        try {
            const r = await fetch('https://meta.matcha.xyz/api/competitions', {
                method: 'POST',
                headers: {'content-type': 'application/json'},
                body: JSON.stringify({chainId: 1, sellAmount: '100000000'})
            });
            return {status: r.status, text: await r.text()};
        } catch(e) { return {error: e.message}; }
    }""")
    print("Evaluation result:", res)
    
    if captured_headers:
        print("\nCaptured Request Headers:")
        h = captured_headers[-1]
        for k in ("x-is-human", "x-kpsdk-ct", "x-kpsdk-cd", "x-kpsdk-v", "user-agent"):
            if k in h:
                print(f"  {k}: {h[k]}")
                
    b.close()
